`Club` createDto에 image 추가
moa-moa/moa-moa-backend pull request #25
Opened 2022-08-22 06:23 UTC by yl9517

Club 생성시 image들을 추가할 수 있습니다.

2022-08-22 06:23 UTC, yl9517 commented
아직 더 작업 남았어요

2022-08-29 04:27 UTC, taesung1993 requested changes

2022-08-29 04:27 UTC, taesung1993 commented on src/image/image.service.ts
> +    clubImages.map(async (image) => {
함수를 목적에 맞게 써주시기 바랍니다.

2022-08-29 05:48 UTC, taesung1993 approved these changes

2022-08-29 06:15 UTC, merged