image파일을 local에 저장합니다
moa-moa/moa-moa-backend pull request #33
Opened 2022-09-09 07:20 UTC by yl9517

2022-09-09 08:40 UTC, taesung1993 commented on src/club/club.controller.ts
> +  ) //업로드파일을 10개로 제한
이 정도만 추가해주시면 될 것 같습니다.
1. 이미지 파일 확장자 제한한다. 다른 형식의 파일이 들어왔을 경우, 에러 처리를 해준다.
2. 업로드 파일을 10개로 제한했지만, 초과해서 요청이 왔을 경우 에러 처리를 해준다.

2022-09-09 08:41 UTC, taesung1993 requested changes
이 정도만 추가해주시면 될 것 같습니다.
### 클럽 이미지 및 유저 이미지
- 이미지 파일 확장자 제한한다. 다른 형식의 파일이 들어왔을 경우, 에러 처리를 해준다.

### 클럽 이미지
- 업로드 파일을 10개로 제한했지만, 초과해서 요청이 왔을 경우 에러 처리를 해준다.

2022-09-13 15:25 UTC, yl9517 commented on prisma/schema.prisma
> +  id           String    @id @unique
id는 `autoincrement`가 아닌 직접 지정한 파일명입니다.
```javascript
// image.controller의 57-59 줄

const fileNameSplit = file.originalname.split('.');
const fileExt = fileNameSplit[fileNameSplit.length - 1];
cb(null, `${Date.now()}.${fileExt}`);
```

2022-09-13 15:29 UTC, yl9517 commented on src/club/dto/create-club.dto.ts
> +  imageIds?: string[];
File을 직접 받는게 아닌 생성된 이미지의  id들을 받습니다

2022-09-13 15:30 UTC, yl9517 commented on src/image/image.controller.ts
> +          return cb(null, false); // FileIntercepter is completely ignoring this.
허용한 파일 확장자가 아니면 fileFilter를 통해 스킵됩니다.

2022-09-13 15:30 UTC, yl9517 commented on src/image/image.controller.ts
> +    FilesInterceptor('files', 10, {
10번째 이미지보다 초과된 이미지들은 스킵됩니다.

2022-09-13 15:34 UTC, yl9517 commented on src/image/image.service.ts
> +  async promiseConnectImages(clubId: number, newImageIds: string[]) {
이미 있는 이미지id라면 그대로 두고, 새로운 id가 있다면 해당 club과 연결시켜줍니다.

2022-09-20 03:38 UTC, taesung1993 requested changes
https://docs.nestjs.com/recipes/serve-static
이거 참조하시고, public 설정좀 해주시기 바랍니다.

클라이언트쪽에서 이미지 참조가 안되네요.

2022-10-02 13:33 UTC, taesung1993 approved these changes

2022-10-03 02:31 UTC, merged