login secure: false로 변경
moa-moa/moa-moa-backend pull request #43
Opened 2022-10-11 02:18 UTC by yl9517

login `secure:false`로 변경
- 사파리에서 쿠키 설정이 되지 않는 문제 해결
- 참고 : https://stackoverflow.com/questions/71882925/cookie-not-being-set-in-safari

2022-10-11 06:31 UTC, taesung1993 requested changes

2022-10-11 06:31 UTC, taesung1993 commented on src/auth/auth.controller.ts
> +      secure: false,
배포까지 생각중이시라면, false값을 직접 주는 것은 좋지 않은 방법 같습니다.

개발 내에서는 브라우저 상관없이 http만을 쓰기때문에, secure에 false를 주더라도, 쿠키 탈취를 걱정하지 않아도 됩니다만,

배포 후 url 스킴은 https이기 때문에 secure는 true가 맞죠.

따라서 장기적 관점으로 판단해볼 때 직접적으로 boolean값을 주기보다는 조건을 이용한 유동적 boolean값을 주는게 더 좋아보입니다.

2022-10-14 20:57 UTC, keizie commented on src/auth/auth.controller.ts
> +      secure: process.env.ENV !== 'dev',
둘의 평가식이 다른 이유가 있나요?

2022-10-15 06:22 UTC, yl9517 commented on src/auth/auth.controller.ts
> +      secure: process.env.ENV !== 'dev',
dev 환경일때는 local에서 http로 구동되므로 httpOnly는 true, 쿠키탈취에 대한 위험이 없으므로 secure은 false로 설정했습니다.
prod환경일때는 반대가 되어야합니다.

2022-10-16 07:18 UTC, taesung1993 approved these changes

2022-10-16 07:43 UTC, merged