Fix/#46 add is image
moa-moa/moa-moa-backend pull request #47
Opened 2022-10-24 08:35 UTC by yl9517

클럽 수정 시 이미지가 있는지 확인합니다.

2022-10-24 10:46 UTC, taesung1993 requested changes

2022-10-24 10:46 UTC, taesung1993 commented on src/club/club.controller.ts
> +        await this.imageService.updateImages(id, updateClubDto.imageIds);
이렇게 하면 에러가 생길 수 밖에 없습니다.

imageIds가 속성이 없으면 length를 불러낼 수 가 없어요.
if(updateClubDto.imageIds && updateClubDto.imageIds.length > 0)
나
if(updateClubDto?.imageIds.length > 0) 
가 더 명확할 듯 싶습니다.

2022-10-24 11:53 UTC, yl9517 commented on src/club/club.controller.ts
> +        await this.imageService.updateImages(id, updateClubDto.imageIds);
앗 아직 이거 수정 전단계였습니다

2022-10-24 14:25 UTC, taesung1993 commented on src/club/club.controller.ts
> +        await this.imageService.updateImages(id, updateClubDto.imageIds);
아하 확인완료

2022-10-24 14:25 UTC, taesung1993 approved these changes

2022-10-25 07:00 UTC, keizie commented on src/club/club.controller.ts
> +        await this.imageService.updateImages(id, updateClubDto.imageIds);
> 앗 아직 이거 수정 전단계였습니다

PR을 draft로 등록하는 기능도 있습니다.

2022-10-25 07:49 UTC, yl9517 commented on src/club/club.controller.ts
> +        await this.imageService.updateImages(id, updateClubDto.imageIds);
오호 감사합니다

2022-10-25 07:49 UTC, merged